language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - npm install

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - npm run build
  - docker --version # print the version for logging
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend scharati/udagram-frontend:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push scharati/udagram-frontend

